name: file-cloud-lab

services:
  api:
    build:
      context: ./api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
      REDIS_URL: redis://redis:6379
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_NAME: ${MONGO_DB_NAME}
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
        awslogs-group: /file-cloud-lab/api
        awslogs-stream: api
        awslogs-create-group: "true"
    networks:
      - backend

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - backend

  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge