export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',

  // Users
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // Files
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',

  // Payments
  PAYMENT_FAILED = 'PAYMENT_FAILED',

  // System
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
